Wwdp201201 20
odevpl/wdp-2012-01 pull request #34
Opened 2020-12-20 11:41 UTC by JustynaZurawiecka

2020-12-20 12:06 UTC, odevpl requested changes

2020-12-20 12:06 UTC, odevpl commented on src/components/features/NewFurniture/NewFurnitureContainer.js
> +  screenWidth: getScreenWidth(state),
Czy funkcja getScreenWidth jest tu potrzebna? Zobacz, masz za zadanie tylko wyciągnąć ze state screenWidth, więc może poprostu: screenWidth: state.screenWidth

2020-12-20 12:06 UTC, odevpl commented on src/components/features/NewFurniture/NewFurnitureContainer.js
> +import { getScreenWidth } from '../../../redux/screenWidthRedux.js';
To chyba można wyrzucić patrząc na niższy komentarz

2020-12-20 12:06 UTC, odevpl commented on src/components/layout/MainLayout/MainLayout.js
> +    window.addEventListener('resize', this.handleResize);
Mam tu pewną uwagę... załużmy, że chcesz zmienić szerokość okna z 1900 na 350... wiąże się to z ponad tysiącem odpaleń tej funkcji, a nam zależy tylko na tym, by funkcja działała, kiedy zmienimy state pomiędzy progami:
desktop, tablet i mobile... proponowałbym logikę do zmiany szerokości zastosować tutaj i gdy szerokość przekroczy któryś próg, dopiero wtedy uruchamiać setState itd

2020-12-20 16:51 UTC, wojciecholejnik approved these changes

2020-12-20 22:15 UTC, JustynaZurawiecka commented on src/components/features/NewFurniture/NewFurniture.js
> +  handleScreenWidth(newScreenWidth) {
Ok pozbyłam się tej funkcji

2020-12-20 22:15 UTC, JustynaZurawiecka commented on src/components/features/NewFurniture/NewFurnitureContainer.js
> +  screenWidth: getScreenWidth(state),
ok

2020-12-20 22:16 UTC, JustynaZurawiecka commented on src/components/features/NewFurniture/NewFurnitureContainer.js
> +import { getScreenWidth } from '../../../redux/screenWidthRedux.js';
ok

2020-12-20 22:18 UTC, JustynaZurawiecka commented on src/components/layout/MainLayout/MainLayout.js
> +    window.addEventListener('resize', this.handleResize);
Ok zmieniłam. Teraz setState jest uruchamiany wtedy, gdy zmienia się typ ekranu: desktop, tablet i mobile

2020-12-21 08:18 UTC, odevpl approved these changes

2020-12-21 08:18 UTC, merged